checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*

build:
  nodes:
    php73:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - php-scrutinizer-run
          -
            command: vendor/bin/phpunit --coverage-clover=coverage73
            coverage:
              file: coverage73
              format: php-clover
    php74:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run
          -
            command: vendor/bin/phpunit --coverage-clover=coverage74
            coverage:
              file: coverage74
              format: php-clover
