blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/owen-it/laravel-auditing/discussions/new?category=ideas
    about: 'For ideas or feature requests, start a new discussion'
  - name: Support Questions & Other
    url: https://github.com/owen-it/laravel-auditing/discussions/new?category=q-a
    about: 'This space is only for reporting bugs. If you have a question or need help use discussions, click:'
  - name: Documentation issue
    url: https://github.com/owen-it/laravel-auditing.com/issues/new
    about: For documentation issues, open a pull request at the owen-it/laravel-auditing.com repository
